baseurl: "https://oulkaid.github.io/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "â†©"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Resume
      url: "resume/"
      weight: 2
    - name: About
      url: "about/"
      weight: 3
    - name: Categories
      url: "categories/"
      weight: 4
    - name: Tags
      url: "tags/"
      weight: 5
    - name: Subscribe
      url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Yihui Xie](https://yihui.org) 2017 -- {Year} | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
