baseurl: "https://oulkaid.github.io/"
languageCode: "en-us"
title: "Oussama Oulkaid"
theme: "xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "â†©"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Curriculum Vitae
      url: "resume/"
      weight: 2
    - name: Projects
      url: "projects/"
      weight: 3

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; {Year} Oussama Oulkaid | Based on [hugo-xmin](https://github.com/yihui/hugo-xmin) theme by [Yihui Xie](https://yihui.org)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
